name: TiDB Cloud Sync
on: [push]

jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup TiDB Cloud CLI
        uses: tidbcloud/setup-tidbcloud-cli@v0
        with:
          api_public_key: ${{ secrets.TIDB_PUBLIC_KEY }}
          api_private_key: ${{ secrets.TIDB_PRIVATE_KEY }}

      - name: Verify Connection
        run: |
          ticloud serverlessess list --project-id ${{ secrets.TIDB_PROJECT_ID }}
